/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { TokenFindManyArgs } from "../../token/base/TokenFindManyArgs";
import { Token } from "../../token/base/Token";
import { TokenWhereUniqueInput } from "../../token/base/TokenWhereUniqueInput";
import { VariableFindManyArgs } from "../../variable/base/VariableFindManyArgs";
import { Variable } from "../../variable/base/Variable";
import { VariableWhereUniqueInput } from "../../variable/base/VariableWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tokens")
  @ApiNestedQuery(TokenFindManyArgs)
  async findTokens(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Token[]> {
    const query = plainToClass(TokenFindManyArgs, request.query);
    const results = await this.service.findTokens(params.id, {
      ...query,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        token: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tokens")
  async connectTokens(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TokenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tokens: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tokens")
  async updateTokens(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TokenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tokens: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tokens")
  async disconnectTokens(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TokenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tokens: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/variables")
  @ApiNestedQuery(VariableFindManyArgs)
  async findVariables(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Variable[]> {
    const query = plainToClass(VariableFindManyArgs, request.query);
    const results = await this.service.findVariables(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/variables")
  async connectVariables(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VariableWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variables: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/variables")
  async updateVariables(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VariableWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variables: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/variables")
  async disconnectVariables(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: VariableWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variables: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
